# Generated by Django 3.2 on 2021-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
