# Generated by Django 3.2 on 2021-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bsapp', '0002_alter_bsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
