# Generated by Django 3.2 on 2021-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bsapp', '0003_alter_bsmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsmodel',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='bsmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
