# Generated by Django 3.2 on 2021-10-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bsapp', '0004_auto_20211011_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsmodel',
            name='phone',
        ),
    ]
