# Generated by Django 3.2 on 2021-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('query', models.TextField(default='', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('illness', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=1)),
                ('health_issue', models.TextField(blank=True, default='', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('addahar', models.CharField(default='', max_length=14)),
                ('age', models.IntegerField(default='', max_length=2)),
            ],
        ),
    ]
