# Generated by Django 3.2 on 2021-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bcmodel',
            old_name='addahar',
            new_name='aadhaar',
        ),
        migrations.AddField(
            model_name='bcmodel',
            name='blood_group',
            field=models.TextField(choices=[('A', 'A+'), ('B', 'B+'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O')], default=''),
        ),
    ]
