# Generated by Django 3.2 on 2021-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0002_auto_20211027_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcmodel',
            name='day',
            field=models.TextField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='', max_length=10),
        ),
    ]
