# Generated by Django 3.2 on 2021-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0004_auto_20211027_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcmodel',
            name='blood_group',
            field=models.TextField(blank=True, choices=[('A', 'A+'), ('B', 'B+'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O')], default=''),
        ),
        migrations.AlterField(
            model_name='bcmodel',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
