# Generated by Django 3.2 on 2021-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0005_auto_20211027_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcmodel',
            name='blood_group',
            field=models.TextField(choices=[('A', 'A+'), ('B', 'B+'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O')], default=''),
        ),
        migrations.AlterField(
            model_name='bcmodel',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
