# Generated by Django 3.2 on 2021-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0006_auto_20211027_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcmodel',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='bcmodel',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A+'), ('B', 'B+'), ('AB', 'AB+'), ('AB', 'AB-'), ('O', 'O')], default='', max_length=2),
        ),
    ]
