# Generated by Django 3.2 on 2021-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0007_auto_20211027_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bcmodel',
            old_name='blood_group',
            new_name='blood',
        ),
        migrations.AlterField(
            model_name='bcmodel',
            name='query',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
