# Generated by Django 3.2 on 2021-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bcapp', '0008_auto_20211027_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcmodel',
            name='month',
            field=models.CharField(choices=[('J', 'January'), ('F', 'February'), ('M', 'March'), ('A', 'April'), ('M', 'May'), ('Ju', 'June'), ('Jl', 'July'), ('Au', 'August'), ('O', 'October'), ('N', 'November'), ('D', 'December')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bcmodel',
            name='year',
            field=models.CharField(choices=[('a', '2021'), ('b', '2022'), ('c', '2023'), ('d', '2024'), ('e', '2025'), ('f', '2026'), ('g', '2027')], default='', max_length=4),
        ),
    ]
